"""Regenerate docs/MODELLING_DIFFERENCES.md from the declarations in code.

    python scripts/generate_modelling_doc.py          # write it
    python scripts/generate_modelling_doc.py --check  # fail if it is stale

Generated, never hand-edited, and `tests/test_modelling_differences.py` runs the
--check so the doc cannot drift from the table it describes. A hand-maintained
list of "ways the simulator differs from the game" is the same artifact as
docs/CARDS_REFERENCE.md, which drifted from the decompile while the tests read it
as an oracle and stayed green.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

DOC_PATH = Path("docs/MODELLING_DIFFERENCES.md")


def render() -> str:
    from sts2_env.cards.derived_values import (
        MODELLING_OVERRIDES,
        undeclared_differences,
    )

    lines = [
        "# Where the simulator deliberately differs from the game",
        "",
        "**Generated by `scripts/generate_modelling_doc.py`. Do not edit by hand** —",
        "`tests/test_modelling_differences.py` regenerates this and fails if it has drifted.",
        "",
        "Card scalars (cost, type, target, rarity, damage, block, keywords, dynamic vars)",
        "are read from `decompiled/` at construction time, so the literals in the card",
        "factories are inert documentation. Behaviour — the `@register_effect` function —",
        "cannot be derived and is hand-written, which is where a difference can appear.",
        "",
        "Anything on this page is a **choice with a stated reason**. Anything NOT on this",
        "page must match the game; `undeclared_differences()` returns the violations and",
        "the test asserts it is empty.",
        "",
        "## Why this file exists",
        "",
        "`SPITE` ran with the wrong effect for months. Its `base_damage` was correct and",
        "derived, but the hand-written function drew a card where the game hits a second",
        "time — and `apply_derived_values` only *updated* dynamic vars the factory had",
        "already declared, so the missing `repeat` was skipped in silence. No add, no",
        "warning. An intentional difference and a forgotten one looked identical, because",
        "both were just an absent dictionary key.",
        "",
        "Declaring them is the point of the table, not an exemption from it.",
        "",
        f"## Declared differences ({len(MODELLING_OVERRIDES)})",
        "",
    ]

    if not MODELLING_OVERRIDES:
        lines += ["None. Every card matches the decompile.", ""]

    for card_id in sorted(MODELLING_OVERRIDES, key=lambda c: c.name):
        override = MODELLING_OVERRIDES[card_id]
        lines.append(f"### {card_id.name}")
        lines.append("")
        lines.append(f"**What differs:** {override.reason}")
        lines.append("")
        if override.fields:
            lines.append(f"**Scalar fields not taken from the decompile:** "
                         f"`{'`, `'.join(sorted(override.fields))}`")
            lines.append("")
        if override.behaviour:
            lines.append(f"**Behavioural difference:** {override.behaviour}")
            lines.append("")
        if override.omitted_vars:
            lines.append(f"**Dynamic vars deliberately absent:** "
                         f"`{'`, `'.join(sorted(override.omitted_vars))}`")
            lines.append("")
        lines.append(f"**When it becomes visible:** {override.observable_when}")
        lines.append("")

    undeclared = undeclared_differences()
    lines.append("## Undeclared differences")
    lines.append("")
    if undeclared:
        lines.append("**These are bugs.** A card carries fewer dynamic vars than the game "
                     "and nothing says why:")
        lines.append("")
        for card_id, missing in sorted(undeclared.items(), key=lambda kv: kv[0].name):
            lines.append(f"- `{card_id.name}` is missing `{missing}`")
        lines.append("")
    else:
        lines.append("None. Every card either matches the decompile or is declared above.")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed doc is out of date")
    args = ap.parse_args()

    content = render()
    if args.check:
        current = DOC_PATH.read_text() if DOC_PATH.is_file() else ""
        if current != content:
            print(f"{DOC_PATH} is out of date. Run:\n"
                  f"    python scripts/generate_modelling_doc.py", file=sys.stderr)
            return 1
        print(f"{DOC_PATH} is up to date.")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(content)
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
